apiVersion: v2
name: grafana
description: A umbrella chart for Grafana
type: application
version: 0.2.0
appVersion: "8.6.1"

dependencies:
  - name: grafana
    version: 8.10.0
    repository: https://grafana.github.io/helm-charts
