apiVersion: v2
name: loki
description: A Loki chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: loki
    version: 5.48.0
    repository: https://grafana.github.io/helm-charts
