global:
  cloudProvider: google
  providerConfigRefName: crossplane-google
  region: "EU"
  bucketName: ""

  google:
    projectID: ""
    hostname: ""
    gateway:
      name: google-gateway-internal
      namespace: google-gateway
    bucket:
      location: ""

loki:
  loki:
    storage:
      type: gcs
    # storage_config:
    #   boltdb_shipper:
    #     shared_store: gcs
    schemaConfig:
      configs:
        - from: "2022-01-11"
          index:
            period: 24h
            prefix: loki_index_
          object_store: gcs
          schema: v12
          store: boltdb-shipper
        - from: "2025-04-22" # Replace with future date
          store: tsdb
          object_store: gcs
          schema: v13
          index:
            prefix: index_
            period: 24h

  read:
    persistence:
      storageClass: standard

  gateway:
    ingress:
      enabled: false
