{{- if eq .Values.global.cloudProvider "google" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-loki
data:
{{ (.Files.Glob "dashboards/loki/*.json").AsConfig | indent 2 }}
---
{{- if not .Values.grafana.datasources }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: 'true'
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: {{ .Values.global.prometheus.hostname }}
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: {{ .Values.global.loki.hostname }}
        jsonData:
          maxLines: 1000
      - name: Google Cloud Monitoring
        type: stackdriver
        access: proxy
        jsonData:
          authenticationType: gce
{{- end }}


{{- end }}