apiVersion: v2
name: keycloak
description: A Keycloak chart for Kubernetes
type: application
version: 0.2.0
appVersion: "2.0"

dependencies:
- name: keycloakx
  version: 2.3.0
  repository: https://codecentric.github.io/helm-charts
