global:
  cloudProvider: ""
  providerConfigRefName: ""
  createProxyRepos: true
  aws:
    account: ""
    clusterOIDC: ""

  google:
    hostname: ""
    projectID: ""
    gateway:
      name: google-gateway-external
      namespace: google-gateway
    bucket:
      location: ""

harbor:
  ipFamily:
    ipv6:
      enabled: false
  logLevel: warning

  cache:
    enabled: false

  persistence:
    persistentVolumeClaim:
      registry:
        size: 30Gi
      jobservice:
        size: 10Gi
      database:
        size: 10Gi
      redis:
        size: 5Gi
      trivy:
        size: 10Gi

  portal:
    replicas: 2
    podAnnotations:
      kube-score/ignore: pod-networkpolicy,pod-probes
    resources:
      limits:
        cpu: 2000m
        memory: 512Mi
        ephemeral-storage: 10Gi
      requests:
        cpu: 10m
        memory: 128Mi
        ephemeral-storage: 128Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  core:
    replicas: 2
    podAnnotations:
      kube-score/ignore: pod-networkpolicy,pod-probes
    resources:
      limits:
        cpu: 2000m
        memory: 512Mi
        ephemeral-storage: 10Gi
      requests:
        cpu: 10m
        memory: 128Mi
        ephemeral-storage: 128Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  jobservice:
    jobLoggers:
      - stdout
    podAnnotations:
      kube-score/ignore: pod-networkpolicy,pod-probes
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
        ephemeral-storage: 10Gi
      requests:
        cpu: 10m
        memory: 128Mi
        ephemeral-storage: 128Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  registry:
    podAnnotations:
      kube-score/ignore: pod-networkpolicy,pod-probes
    registry:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
          ephemeral-storage: 10Gi
        requests:
          cpu: 10m
          memory: 128Mi
          ephemeral-storage: 128Mi
    controller:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
          ephemeral-storage: 10Gi
        requests:
          cpu: 10m
          memory: 128Mi
          ephemeral-storage: 128Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  database:
    type: internal
    podAnnotations:
      kube-score/ignore: pod-networkpolicy,pod-probes
    internal:
      readinessProbe:
        timeoutSeconds: 20
      livenessProbe:
        timeoutSeconds: 20
      resources:
        limits:
          cpu: 2000m
          memory: 2Gi
          ephemeral-storage: 10Gi
        requests:
          cpu: 100m
          memory: 256Mi
          ephemeral-storage: 100Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 90
              preference:
                matchExpressions:
                  - key: tools
                    operator: In
                    values:
                      - "true"
      tolerations:
        - key: "tools"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      initContainer:
        migrator:
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
              ephemeral-storage: 10Gi
            requests:
              cpu: 1m
              memory: 64Mi
              ephemeral-storage: 100Mi
        permissions:
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
              ephemeral-storage: 10Gi
            requests:
              cpu: 1m
              memory: 64Mi
              ephemeral-storage: 100Mi
  redis:
    type: internal
    podAnnotations:
      kube-score/ignore: pod-networkpolicy,pod-probes
    internal:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
          ephemeral-storage: 10Gi
        requests:
          cpu: 10m
          memory: 32Mi
          ephemeral-storage: 128Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 90
              preference:
                matchExpressions:
                  - key: tools
                    operator: In
                    values:
                      - "true"
      tolerations:
        - key: "tools"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

  exporter:
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
        ephemeral-storage: 10Gi
      requests:
        cpu: 10m
        memory: 32Mi
        ephemeral-storage: 128Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  trivy:
    podAnnotations:
      kube-score/ignore: pod-networkpolicy
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
        ephemeral-storage: 128Mi
      limits:
        cpu: 1
        memory: 1Gi
        ephemeral-storage: 10Gi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
