global:
  cloudProvider: ""
  providerConfigRefName: ""
  nodeRoleName: ""
  nodeRoleARN: ""
  createNodepool: false

# https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/values.yaml

# Currently this has to be manually added to kube-system/aws-auth configmap to allow karpenter to add nodes to the cluster
#     - "groups":
#       - "system:bootstrappers"
#       - "system:nodes"
#       "rolearn": "arn:aws:iam::877483565445:role/{{ .Release.Name }}-karpenter-node-role"
#       "username": "system:node:{{EC2PrivateDNSName}}"

karpenter:
  serviceAccount:
    create: false
    name: karpenter
  replicas: 1
  controller:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
        ephemeral-storage: 1Gi
      limits:
        cpu: 1
        memory: 1Gi
        ephemeral-storage: 2Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"

  settings:
    clusterName: ""
    isolatedVPC: true
