apiVersion: v2
name: crossplane
description: Crossplane operator chart
type: application
version: 0.1.1
appVersion: "1.1"

dependencies:
- name: crossplane
  version: 1.15.5
  repository: https://charts.crossplane.io/stable
