{{- if eq .Values.global.cloudProvider "aws" }}
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: {{ .Release.Name }}
spec:
  forProvider:
    name: {{ .Release.Name }}
    document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
              "Sid": "VisualEditor0",
              "Effect": "Allow",
              "Action": "route53:ChangeResourceRecordSets",
              "Resource": "arn:aws:route53:::hostedzone/*"
          },
          {
              "Sid": "VisualEditor1",
              "Effect": "Allow",
              "Action": [
                  "route53:ListHostedZones",
                  "route53:ListResourceRecordSets"
              ],
              "Resource": "*"
          }{{- if .Values.global.aws.assumeRole -}},
          {
              "Sid": "VisualEditor2",
              "Effect": "Allow",
              "Action": [
                  "sts:AssumeRole"
              ],
              "Resource": "{{ .Values.global.aws.assumeRole }}"
          }
{{- end }}
        ]
      }

  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

{{- end }}
