apiVersion: v2
name: istio-istiod
description: istio
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: istiod
    version: 1.25.2
    repository: https://istio-release.storage.googleapis.com/charts
