{{- if eq .Values.global.cloudProvider "aws" }}

apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: {{ .Release.Name }}-karpenter-controller-policy
spec:
  forProvider:
    name: {{ .Release.Name }}-karpenter-controller-policy
    document: |
      {
          "Statement": [
              {
                  "Action": [
                      "ssm:GetParameter",
                      "ec2:DescribeImages",
                      "ec2:RunInstances",
                      "ec2:DescribeSubnets",
                      "ec2:DescribeSecurityGroups",
                      "ec2:DescribeLaunchTemplates",
                      "ec2:DescribeInstances",
                      "ec2:DescribeInstanceTypes",
                      "ec2:DescribeInstanceTypeOfferings",
                      "ec2:DescribeAvailabilityZones",
                      "ec2:DeleteLaunchTemplate",
                      "ec2:CreateTags",
                      "ec2:CreateLaunchTemplate",
                      "ec2:CreateFleet",
                      "ec2:DescribeSpotPriceHistory",
                      "pricing:GetProducts"
                  ],
                  "Effect": "Allow",
                  "Resource": "*",
                  "Sid": "Karpenter"
              },
              {
                  "Action": "ec2:TerminateInstances",
                  "Condition": {
                      "StringLike": {
                          "ec2:ResourceTag/karpenter.sh/nodepool": "*"
                      }
                  },
                  "Effect": "Allow",
                  "Resource": "*",
                  "Sid": "ConditionalEC2Termination"
              },
              {
                  "Effect": "Allow",
                  "Action": "iam:PassRole",
                  "Resource": "arn:aws:iam::{{ .Values.global.aws.account }}:role/{{ .Release.Name }}-karpenter-node-role",
                  "Sid": "PassNodeIAMRole"
              },
              {
                  "Effect": "Allow",
                  "Action": "eks:DescribeCluster",
                  "Resource": "arn:aws:eks:{{ .Values.global.aws.region }}:{{ .Values.global.aws.account }}:cluster/{{ .Values.karpenter.settings.clusterName }}",
                  "Sid": "EKSClusterEndpointLookup"
              },
              {
                  "Sid": "AllowScopedInstanceProfileCreationActions",
                  "Effect": "Allow",
                  "Resource": "*",
                  "Action": [
                  "iam:CreateInstanceProfile"
                  ],
                  "Condition": {
                  "StringEquals": {
                      "aws:RequestTag/kubernetes.io/cluster/{{ .Values.karpenter.settings.clusterName }}": "owned",
                      "aws:RequestTag/topology.kubernetes.io/region": "{{ .Values.global.aws.region }}"
                  },
                  "StringLike": {
                      "aws:RequestTag/karpenter.k8s.aws/ec2nodeclass": "*"
                  }
                  }
              },
              {
                  "Sid": "AllowScopedInstanceProfileTagActions",
                  "Effect": "Allow",
                  "Resource": "*",
                  "Action": [
                  "iam:TagInstanceProfile"
                  ],
                  "Condition": {
                  "StringEquals": {
                      "aws:ResourceTag/kubernetes.io/cluster/{{ .Values.karpenter.settings.clusterName }}": "owned",
                      "aws:ResourceTag/topology.kubernetes.io/region": "{{ .Values.global.aws.region }}",
                      "aws:RequestTag/kubernetes.io/cluster/{{ .Values.karpenter.settings.clusterName }}": "owned",
                      "aws:RequestTag/topology.kubernetes.io/region": "{{ .Values.global.aws.region }}"
                  },
                  "StringLike": {
                      "aws:ResourceTag/karpenter.k8s.aws/ec2nodeclass": "*",
                      "aws:RequestTag/karpenter.k8s.aws/ec2nodeclass": "*"
                  }
                  }
              },
              {
                  "Sid": "AllowScopedInstanceProfileActions",
                  "Effect": "Allow",
                  "Resource": "*",
                  "Action": [
                  "iam:AddRoleToInstanceProfile",
                  "iam:RemoveRoleFromInstanceProfile",
                  "iam:DeleteInstanceProfile"
                  ],
                  "Condition": {
                  "StringEquals": {
                      "aws:ResourceTag/kubernetes.io/cluster/{{ .Values.karpenter.settings.clusterName }}": "owned",
                      "aws:ResourceTag/topology.kubernetes.io/region": "{{ .Values.global.aws.region }}"
                  },
                  "StringLike": {
                      "aws:ResourceTag/karpenter.k8s.aws/ec2nodeclass": "*"
                  }
                  }
              },
              {
                  "Sid": "AllowInstanceProfileReadActions",
                  "Effect": "Allow",
                  "Resource": "*",
                  "Action": "iam:GetInstanceProfile"
              }
          ],
          "Version": "2012-10-17"
      }

  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

{{- end }}