apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-cloudplatform
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-cloudplatform:v1.9.0
  runtimeConfigRef:
    name: {{.Release.Name}}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-storage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-storage:v1.10.0
  runtimeConfigRef:
    name: {{.Release.Name}}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-secretmanager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-secretmanager:v1.10.0
  runtimeConfigRef:
    name: {{.Release.Name}}

{{- if .Values.global.extraProviders }}
{{- range .Values.global.extraProviders }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: {{ .package }}
  runtimeConfigRef:
    name: {{ $.Release.Name }}
{{- end }}
{{- end }}
