{{- if eq .Values.global.cloudProvider "aws" }}

apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Values.global.bucketName }}
  annotations:
    crossplane.io/external-name: {{ .Values.global.bucketName }}
spec:
  forProvider:
    acl: private
    locationConstraint: {{ .Values.global.aws.region }}
    objectOwnership: BucketOwnerPreferred
    publicAccessBlockConfiguration:
      blockPublicPolicy: true
      blockPublicAcls: true
      ignorePublicAcls: true
      restrictPublicBuckets: true
    accelerateConfiguration:
      status: Enabled
    versioningConfiguration:
      status: Suspended
    serverSideEncryptionConfiguration:
      rules:
      - applyServerSideEncryptionByDefault:
          {{- if .Values.global.aws.kmsKeyId }}
          kmsMasterKeyId: {{ .Values.global.aws.kmsKeyId }}
          sseAlgorithm: aws:kms
          {{- else }}
          sseAlgorithm: AES256
          {{- end }}
        bucketKeyEnabled: true
    lifecycleConfiguration:
      {{- if .Values.global.aws.bucketLifecycleRules }}
      rules:
        {{- toYaml .Values.global.aws.bucketLifecycleRules | nindent 8 }}
        {{- else }}
      {{- end }}
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

{{- end }}
