{{- if eq .Values.global.cloudProvider "aws" }}

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.aws.account }}:role/{{ .Release.Name }}
  name: mimir

{{- end }}