name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:   
    runs-on: ubuntu-latest
    name: Publish
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Authenticate with GitHub CLI
      run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: create_release
      run: |
        RELEASE_URL=$(gh release create ${GITHUB_REF##refs/tags/} \
        --title "Release ${GITHUB_REF##refs/tags/}" \
        --generate-notes \
        --notes-from-tag \
        --draft=false \
        --latest=true \
        --prerelease=false)
        echo "RELEASE_URL=$RELEASE_URL" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
