apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
    category: application
  annotations:
    kube-score/ignore: pod-networkpolicy,pod-probes
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: resources-config
          configMap:
            name: {{ .Release.Name }}-resources
      containers:
      - name: {{ .Release.Name }}
        image: entigolabs/developer-portal-agent:main-62
        volumeMounts:
        - mountPath: /config/
          name: resources-config
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ .Release.Name }}
      nodeSelector:
        beta.kubernetes.io/arch: amd64

